// Code generated by internal/cmd/genapi. DO NOT EDIT.

package server

import (
	"context"
	"net/http"
	"net/url"
	"time"

	"github.com/ably/ably-pubsub-go/internal/ably"
	"github.com/ably/ably-pubsub-go/internal/ably/objects"
)

// Types.

// AblyVCDiffDecoder is a production-ready implementation of the VCDiffDecoder interface
// that uses the official ably/vcdiff-go library for delta decoding.
// Implements VCDiffDecoder interface for decoding VCDiff-encoded delta messages (PC3).
type AblyVCDiffDecoder = ably.AblyVCDiffDecoder

// Auth creates Ably [TokenRequest] objects and obtains Ably Tokens from Ably to
// subsequently issue to less trusted clients.
type Auth = ably.Auth

// AuthOption configures authentication/authorization for a [HTTPClient] or [Realtime]
// instance or operation.
type AuthOption = ably.AuthOption

// ChannelDetails contains the details of a [HTTPChannel] or [RealtimeChannel] object
// such as its ID and [ChannelStatus].
type ChannelDetails = ably.ChannelDetails

// ChannelEvent describes the events emitted by a [HTTPChannel] or [RealtimeChannel] object.
// An event is either an UPDATE or a [ChannelState].
type ChannelEvent = ably.ChannelEvent

type ChannelEventEmitter = ably.ChannelEventEmitter

// ChannelMetrics contains the metrics associated with a [HTTPChannel] or [RealtimeChannel],
// such as the number of publishers, subscribers and connections it has.
type ChannelMetrics = ably.ChannelMetrics

// ChannelMode Describes the possible flags used to configure client capabilities, using [ChannelOption].
type ChannelMode = ably.ChannelMode

// ChannelOccupancy contains the metrics of a [HTTPChannel] or [RealtimeChannel] object.
type ChannelOccupancy = ably.ChannelOccupancy

// ChannelOption configures a channel.
type ChannelOption = ably.ChannelOption

// CP2
type ChannelProperties = ably.ChannelProperties

// ChannelState describes the possible states of a [HTTPChannel] or [RealtimeChannel] object.
type ChannelState = ably.ChannelState

// ChannelStateChange contains state change information emitted by [HTTPChannel] and [RealtimeChannel] objects.
// A ChannelStateChange is the data associated with a ChannelEvent.
type ChannelStateChange = ably.ChannelStateChange

// ChannelStatus contains the status of a [HTTPChannel] or [RealtimeChannel] object such as whether
// it is active and its [ChannelOccupancy].
type ChannelStatus = ably.ChannelStatus

// CipherAlgorithm is a supported algorithm for channel encryption.
type CipherAlgorithm = ably.CipherAlgorithm

// CipherMode is a supported cipher mode for channel encryption.
type CipherMode = ably.CipherMode

// CipherParams sets the properties to configure encryption for a [HTTPChannel] or
// [RealtimeChannel] object (TZ1).
type CipherParams = ably.CipherParams

// ClientOption configures a [HTTPClient] or [Realtime] instance.
//
// See: https://www.ably.io/documentation/realtime/usage#client-options
type ClientOption = ably.ClientOption

// Connection represents a single connection Realtime instantiates for communication with Ably servers.
// It also enables the management of a connection to Ably.
type Connection = ably.Connection

// ConnectionEvent describes the events emitted by a [Connection] object.
// An event is either an [ConnectionEventUpdate] or [ConnectionState} change event.
type ConnectionEvent = ably.ConnectionEvent

type ConnectionEventEmitter = ably.ConnectionEventEmitter

// ConnectionState describes the realtime [Connection] object states.
type ConnectionState = ably.ConnectionState

// ConnectionStateChange Contains [ConnectionState]change information emitted by the [Connection] object.
// A ConnectionStateChange is the data associated with a ConnectionEvent.
type ConnectionStateChange = ably.ConnectionStateChange

// DecodingContext provides context needed for decoding messages, including delta support.
type DecodingContext = ably.DecodingContext

// DeltaExtras describes a message whose payload is a "vcdiff"-encoded delta generated with respect to a base message (DE1, DE2).
type DeltaExtras = ably.DeltaExtras

// DeriveOptions allows options to be used in creating a derived channel
type DeriveOptions = ably.DeriveOptions

type Direction = ably.Direction

// ErrorCode is the type for predefined Ably error codes.
type ErrorCode = ably.ErrorCode

// ErrorInfo is a generic Ably error object that contains an Ably-specific status code, and a generic status code.
// Errors returned from the Ably server are compatible with the ErrorInfo structure and should result in errors
// that inherit from ErrorInfo. It may contain underlying error value which caused the failure.
type ErrorInfo = ably.ErrorInfo

// GetPresenceOption configures a call to HTTPPresence.Get or RealtimePresence.Get.
type GetPresenceOption = ably.GetPresenceOption

// HTTPChannel is the interface for REST API operations on a channel.
// It enables messages to be published and historic messages to be retrieved for a channel.
type HTTPChannel = ably.HTTPChannel

// HTTPChannels provides an API for managing collection of HTTPChannel.
// This is safe for concurrent use.
type HTTPChannels = ably.HTTPChannels

type HTTPPaginatedItems = ably.HTTPPaginatedItems

// HTTPPaginatedResponse is a superset of [PaginatedResult] which represents a page of results plus metadata
// indicating the relative queries available to it. HttpPaginatedResponse additionally carries information
// about the response to an HTTP request.
// A HTTPPaginatedResponse is an iterator for the response of a REST request.
//
// See package-level documentation => [ably] Pagination for more details.
type HTTPPaginatedResponse = ably.HTTPPaginatedResponse

// HTTPPresence enables the retrieval of the current and historic presence set for a channel.
type HTTPPresence = ably.HTTPPresence

// HTTPRequest represents a request prepared by the HTTPClient.Request method, ready
// to be performed by its Pages or Items methods.
type HTTPRequest = ably.HTTPRequest

// A HistoryOption configures a call to HTTPChannel.History or RealtimeChannel.History.
type HistoryOption = ably.HistoryOption

// HistoryRequest represents a request prepared by the HTTPChannel.History or
// RealtimeChannel.History method, ready to be performed by its Pages or Items methods.
type HistoryRequest = ably.HistoryRequest

type LogLevel = ably.LogLevel

// Logger is an interface for ably loggers.
type Logger = ably.Logger

// Message contains an individual message that is sent to, or received from, Ably.
type Message = ably.Message

// MessageAction represents the type of message operation (TM5).
type MessageAction = ably.MessageAction

// MessageVersion contains version information for a message (TM2s).
// When received from the server, Serial and Timestamp are server-populated.
// When sending an update/delete/append, ClientID, Description, and Metadata
// are user-provided via UpdateOption functions (mapped from MOP2a/MOP2b/MOP2c).
type MessageVersion = ably.MessageVersion

type MessagesPaginatedItems = ably.MessagesPaginatedItems

// A MessagesPaginatedResult is an iterator for the result of a History request.
//
// See package-level documentation => [ably] Pagination for details about history pagination.
type MessagesPaginatedResult = ably.MessagesPaginatedResult

type PaginateParams = ably.PaginateParams

// PaginatedResult is a generic iterator for PaginatedResult pagination.
// Items decoding is delegated to type-specific wrappers.
//
// See "Paginated results" section in the package-level documentation.
type PaginatedResult = ably.PaginatedResult

type PeriodUnit = ably.PeriodUnit

// PresenceAction describes the possible actions members in the presence set can emit (TP2).
type PresenceAction = ably.PresenceAction

// A PresenceGetOption is an optional parameter for RealtimePresence.GetWithOptions.
type PresenceGetOption = ably.PresenceGetOption

// PresenceHistoryOption configures a call to HTTPChannel.History or RealtimeChannel.History.
type PresenceHistoryOption = ably.PresenceHistoryOption

type PresenceMessage = ably.PresenceMessage

type PresencePaginatedItems = ably.PresencePaginatedItems

// A PresencePaginatedResult is an iterator for the result of a PresenceHistory request.
//
// See package-level documentation => [ably] Pagination for more details.
type PresencePaginatedResult = ably.PresencePaginatedResult

// PresenceRequest represents a request prepared by the HTTPPresence.History or
// RealtimePresence.History method, ready to be performed by its Pages or Items methods.
type PresenceRequest = ably.PresenceRequest

// PublishMultipleOption is an optional parameter for
// HTTPChannel.Publish and HTTPChannel.PublishMultiple.
//
// TODO: This started out as just an option for PublishMultiple, but has since
//
//	been added as an option for Publish too, so it should be renamed to
//	PublishOption when we perform the next major version bump to 2.x.x.
type PublishMultipleOption = ably.PublishMultipleOption

// PublishResult contains the result of a publish operation with serial tracking.
// The spec (PBR2a) defines PublishResult with a serials array, but per RSL1n1/RTL6j1,
// SDKs may implement alternatives where adding a response value would be a breaking
// API change. This SDK returns one PublishResult per message for ergonomics.
type PublishResult = ably.PublishResult

// PushStats provides details the stats on push notifications.
type PushStats = ably.PushStats

// RealtimeChannel represents a single named message/presence channel.
// It enables messages to be published and subscribed to. Also enables historic messages to be retrieved and
// provides access to the [RealtimePresence] object of a channel.
type RealtimeChannel = ably.RealtimeChannel

// RealtimeChannels is a goroutine-safe container for realtime channels that allows for creating,
// deleting and iterating over existing channels.
// Creates and destroys [HTTPChannel] and [RealtimeChannel] objects.
type RealtimeChannels = ably.RealtimeChannels

// RealtimeExperimentalObjects exposes a method to publish LiveObject messages on a Realtime channel.
// It requires the LiveObjects plugin to be configured see ably-go/ably/objects/liveobjects.go.
//
// NOTE: this option is experimental, the LiveObjects plugin API may change in a
// backwards incompatible way between minor/patch versions. Once the API has been finalised,
// a new non-experimental option will be added, and this one will be removed.
//
// [LiveObjects]: https://ably.com/docs/liveobjects
type RealtimeExperimentalObjects = ably.RealtimeExperimentalObjects

// RealtimePresence represents a single presence map of a particular channel.
// It allows entering, leaving and updating presence state for the current client or on behalf of other client.
// It enables the presence set to be entered and subscribed to, and the historic presence set to be retrieved for a channel.
type RealtimePresence = ably.RealtimePresence

// RecoveryKeyContext contains the properties required to recover existing connection.
type RecoveryKeyContext = ably.RecoveryKeyContext

// RequestOption configures a call to HTTPClient.Request.
type RequestOption = ably.RequestOption

type ScopeParams = ably.ScopeParams

// Stats contains application statistics for a specified time interval and time period.
type Stats = ably.Stats

// StatsConnectionTypes contains a breakdown of summary stats data for different (TLS vs non-TLS) connection types.
type StatsConnectionTypes = ably.StatsConnectionTypes

// StatsMessageCount contains the aggregate counts for messages and data transferred.
type StatsMessageCount = ably.StatsMessageCount

type StatsMessageDirections = ably.StatsMessageDirections

type StatsMessageTraffic = ably.StatsMessageTraffic

// StatsMessageTypes contains a breakdown of summary stats data for different (channel vs presence) message types.
type StatsMessageTypes = ably.StatsMessageTypes

// A StatsOption configures a call to HTTPClient.Stats or Realtime.Stats.
type StatsOption = ably.StatsOption

type StatsPaginatedItems = ably.StatsPaginatedItems

// A StatsPaginatedResult is an iterator for the result of a Stats request.
//
// See package-level documentation => [ably] Pagination for handling stats pagination.
type StatsPaginatedResult = ably.StatsPaginatedResult

type StatsPushNotificationFailures = ably.StatsPushNotificationFailures

type StatsPushNotifications = ably.StatsPushNotifications

type StatsPushTransportTypeCounter = ably.StatsPushTransportTypeCounter

type StatsRates = ably.StatsRates

type StatsReactorRates = ably.StatsReactorRates

// StatsRequest represents a request prepared by the HTTPClient.Stats or
// Realtime.Stats method, ready to be performed by its Pages or Items methods.
type StatsRequest = ably.StatsRequest

type StatsRequestCount = ably.StatsRequestCount

type StatsResourceCount = ably.StatsResourceCount

type StatsXchgMessages = ably.StatsXchgMessages

// TokenDetails contains an Ably Token and its associated metadata.
type TokenDetails = ably.TokenDetails

// TokenParams contains token params to be sent to ably to get auth token
type TokenParams = ably.TokenParams

// TokenRequest contains tokenparams with extra details, sent to ably for getting auth token
type TokenRequest = ably.TokenRequest

// TokenString is the string representation of an authentication token.
type TokenString = ably.TokenString

// Tokener is or can be used to get a [TokenDetails].
type Tokener = ably.Tokener

// UpdateDeleteResult contains the result of an update, delete, or append operation (UDR1).
type UpdateDeleteResult = ably.UpdateDeleteResult

// UpdateOption is a functional option for message update operations.
type UpdateOption = ably.UpdateOption

// VCDiffDecoder provides an interface for decoding vcdiff-encoded message payloads (VD1, VD2).
// This interface must be implemented by plugins that provide vcdiff delta decoding functionality.
type VCDiffDecoder = ably.VCDiffDecoder

// LiveObjects types. The Objects prefix keeps them apart from the
// same-named types of the main API once both live in one package.

type ObjectsCounter = objects.Counter

type ObjectsCounterCreate = objects.CounterCreate

type ObjectsCounterCreateWithObjectId = objects.CounterCreateWithObjectId

type ObjectsCounterInc = objects.CounterInc

type ObjectsCounterOp = objects.CounterOp

type ObjectsData = objects.Data

type ObjectsMap = objects.Map

type ObjectsMapCreate = objects.MapCreate

type ObjectsMapCreateWithObjectId = objects.MapCreateWithObjectId

type ObjectsMapEntry = objects.MapEntry

type ObjectsMapOp = objects.MapOp

type ObjectsMapRemove = objects.MapRemove

type ObjectsMapSemantics = objects.MapSemantics

type ObjectsMapSet = objects.MapSet

type ObjectsMessage = objects.Message

type ObjectsObjectDelete = objects.ObjectDelete

type ObjectsOperation = objects.Operation

type ObjectsOperationAction = objects.OperationAction

// Plugin is used to add LiveObject functionality to a realtime client:
//
//	client, err := NewRealtime(
//		WithKey(...),
//		WithExperimentalObjectsPlugin(myObjectsPlugin),
//	)
//
// The plugin is used to prepare object messages to be published in the
// realtime channel's publishObjects method, and is used to handle incoming
// object and object sync messages.
type ObjectsPlugin = objects.Plugin

type ObjectsState = objects.State

// Constants and variables.

// Crypto contains the properties required to configure the encryption of [Message] payloads.
var Crypto = ably.Crypto

const ErrNotSet = ably.ErrNotSet

const ErrBadRequest = ably.ErrBadRequest

const ErrInvalidCredential = ably.ErrInvalidCredential

const ErrInvalidClientID = ably.ErrInvalidClientID

const ErrDeltaDecodingFailed = ably.ErrDeltaDecodingFailed

const ErrMissingPlugin = ably.ErrMissingPlugin

const ErrUnauthorized = ably.ErrUnauthorized

const ErrInvalidCredentials = ably.ErrInvalidCredentials

const ErrIncompatibleCredentials = ably.ErrIncompatibleCredentials

const ErrInvalidUseOfBasicAuthOverNonTLSTransport = ably.ErrInvalidUseOfBasicAuthOverNonTLSTransport

const ErrTokenErrorUnspecified = ably.ErrTokenErrorUnspecified

const ErrErrorFromClientTokenCallback = ably.ErrErrorFromClientTokenCallback

const ErrForbidden = ably.ErrForbidden

const ErrNotFound = ably.ErrNotFound

const ErrMethodNotAllowed = ably.ErrMethodNotAllowed

const ErrInternalError = ably.ErrInternalError

const ErrInternalChannelError = ably.ErrInternalChannelError

const ErrInternalConnectionError = ably.ErrInternalConnectionError

const ErrTimeoutError = ably.ErrTimeoutError

const ErrConnectionFailed = ably.ErrConnectionFailed

const ErrConnectionSuspended = ably.ErrConnectionSuspended

const ErrConnectionClosed = ably.ErrConnectionClosed

const ErrDisconnected = ably.ErrDisconnected

const ErrProtocolError = ably.ErrProtocolError

const ErrChannelOperationFailed = ably.ErrChannelOperationFailed

const ErrChannelOperationFailedInvalidChannelState = ably.ErrChannelOperationFailedInvalidChannelState

const PeriodMinute = ably.PeriodMinute

const PeriodHour = ably.PeriodHour

const PeriodDay = ably.PeriodDay

const PeriodMonth = ably.PeriodMonth

const LogNone = ably.LogNone

const LogError = ably.LogError

const LogWarning = ably.LogWarning

const LogInfo = ably.LogInfo

const LogVerbose = ably.LogVerbose

const LogDebug = ably.LogDebug

const Port = ably.Port

const TLSPort = ably.TLSPort

const Backwards = ably.Backwards

const Forwards = ably.Forwards

// ChannelModePresence allows the attached channel to enter Presence.
const ChannelModePresence = ably.ChannelModePresence

// ChannelModePublish allows for messages to be published on the attached channel.
const ChannelModePublish = ably.ChannelModePublish

// ChannelModeSubscribe allows the attached channel to subscribe to messages.
const ChannelModeSubscribe = ably.ChannelModeSubscribe

// ChannelModePresenceSubscribe allows the attached channel to subscribe to Presence updates.
const ChannelModePresenceSubscribe = ably.ChannelModePresenceSubscribe

// ChannelModeObjectSubscribe allows the attached channel to subscribe to Objects updates.
const ChannelModeObjectSubscribe = ably.ChannelModeObjectSubscribe

// ChannelModeObjectPublish allows for objects messages to be published on the attached channel.
const ChannelModeObjectPublish = ably.ChannelModeObjectPublish

const CipherAES = ably.CipherAES

const CipherCBC = ably.CipherCBC

// AblyAgentHeaderName is the name of the Ably-Agent header (RSC7d), exported for
// use by test helpers that issue their own requests to Ably.
const AblyAgentHeaderName = ably.AblyAgentHeaderName

const MessageActionUnknown = ably.MessageActionUnknown

const MessageActionCreate = ably.MessageActionCreate

const MessageActionUpdate = ably.MessageActionUpdate

const MessageActionDelete = ably.MessageActionDelete

const MessageActionMeta = ably.MessageActionMeta

const MessageActionMessageSummary = ably.MessageActionMessageSummary

const MessageActionAppend = ably.MessageActionAppend

// PresenceActionAbsent specifies a member is not present in the channel.
const PresenceActionAbsent = ably.PresenceActionAbsent

// PresenceActionPresent denotes when subscribing to presence events on a channel that already has members present,
// this event is emitted for every member already present on the channel before the subscribe listener was registered.
const PresenceActionPresent = ably.PresenceActionPresent

// PresenceActionEnter denotes that new member has entered the channel.
const PresenceActionEnter = ably.PresenceActionEnter

// PresenceActionLeave is a member who was present has now left the channel. This may be a result of an explicit
// request to leave or implicitly when detaching from the channel. Alternatively, if a member's connection is
// abruptly disconnected and they do not resume their connection within a minute, Ably treats this as a
// leave event as the client is no longer present.
const PresenceActionLeave = ably.PresenceActionLeave

// PresenceActionUpdate is a already present member has updated their member data. Being notified of member data
// updates can be very useful, for example, it can be used to update the status of a user when they are
// typing a message.
const PresenceActionUpdate = ably.PresenceActionUpdate

// StatGranularityMinute specifies interval unit over which statistics are gathered as minutes.
const StatGranularityMinute = ably.StatGranularityMinute

// StatGranularityHour specifies interval unit over which statistics are gathered as hours.
const StatGranularityHour = ably.StatGranularityHour

// StatGranularityDay specifies interval unit over which statistics are gathered as days.
const StatGranularityDay = ably.StatGranularityDay

// StatGranularityMonth specifies interval unit over which statistics are gathered as months.
const StatGranularityMonth = ably.StatGranularityMonth

// ConnectionStateInitialized - A connection with this state has been initialized
// but no connection has yet been attempted.
var ConnectionStateInitialized = ably.ConnectionStateInitialized

// ConnectionStateConnecting - A connection attempt has been initiated.
// The connecting state is entered as soon as the library has completed initialization,
// and is reentered each time connection is re-attempted following disconnection.
var ConnectionStateConnecting = ably.ConnectionStateConnecting

// ConnectionStateConnected - A connection exists and is active.
var ConnectionStateConnected = ably.ConnectionStateConnected

// ConnectionStateDisconnected - A temporary failure condition. No current connection exists
// because there is no network connectivity or no host is available.
// The disconnected state is entered if an established connection is dropped,
// or if a connection attempt was unsuccessful. In the disconnected state the library will periodically attempt
// to open a new connection (approximately every 15 seconds), anticipating that the connection will
// be re-established soon and thus connection and channel continuity will be possible.
// In this state, developers can continue to publish messages as they are automatically placed in a local queue,
// to be sent as soon as a connection is reestablished. Messages published by other clients
// while this client is disconnected will be delivered to it upon reconnection, so long as
// the connection was resumed within 2 minutes. After 2 minutes have elapsed, recovery is no longer possible
// and the connection will move to the SUSPENDED state.
var ConnectionStateDisconnected = ably.ConnectionStateDisconnected

// ConnectionStateSuspended - A long term failure condition. No current connection exists
// because there is no network connectivity or no host is available. The suspended state is entered
// after a failed connection attempt if there has then been no connection for a period of two minutes.
// In the suspended state, the library will periodically attempt to open a new connection every 30 seconds.
// Developers are unable to publish messages in this state. A new connection attempt can also be triggered
// by an explicit call to Connection.Connect. Once the connection has been re-established,
// channels will be automatically re-attached. The client has been disconnected for too long for them
// to resume from where they left off, so if it wants to catch up on messages published by other clients
// while it was disconnected, it needs to use the History API.
var ConnectionStateSuspended = ably.ConnectionStateSuspended

// ConnectionStateClosing is when an explicit request by the developer to close the connection has been sent to
// the Ably service. If a reply is not received from Ably within a short period of time,
// the connection is forcibly terminated and the connection state becomes CLOSED.
var ConnectionStateClosing = ably.ConnectionStateClosing

// ConnectionStateClosed - The connection has been explicitly closed by the client.
// In the closed state, no reconnection attempts are made automatically by the library,
// and clients may not publish messages. No connection state is preserved by the service or by the library.
// A new connection attempt can be triggered by an explicit call to Connection.Connect,
// which results in a new connection.
var ConnectionStateClosed = ably.ConnectionStateClosed

// ConnectionStateFailed - This state is entered if the client library encounters a failure condition
// that it cannot recover from. This may be a fatal connection error received from the Ably service,
// for example an attempt to connect with an incorrect API key, or a local terminal error,
// for example the token in use has expired and the library does not have any way to renew it.
// In the failed state, no reconnection attempts are made automatically by the library, and
// clients may not publish messages. A new connection attempt can be triggered by an explicit call
// to Connection.Connect.
var ConnectionStateFailed = ably.ConnectionStateFailed

// ConnectionEventInitialized - A connection with this state has been initialized
// but no connection has yet been attempted.
var ConnectionEventInitialized = ably.ConnectionEventInitialized

// ConnectionEventConnecting - A connection attempt has been initiated.
// The connecting state is entered as soon as the library has completed initialization,
// and is reentered each time connection is re-attempted following disconnection.
var ConnectionEventConnecting = ably.ConnectionEventConnecting

// ConnectionEventConnected - A connection exists and is active.
var ConnectionEventConnected = ably.ConnectionEventConnected

// ConnectionEventDisconnected - A temporary failure condition. No current connection exists
// because there is no network connectivity or no host is available.
// The disconnected state is entered if an established connection is dropped,
// or if a connection attempt was unsuccessful. In the disconnected state the library will periodically attempt
// to open a new connection (approximately every 15 seconds), anticipating that the connection will
// be re-established soon and thus connection and channel continuity will be possible.
// In this state, developers can continue to publish messages as they are automatically placed in a local queue,
// to be sent as soon as a connection is reestablished. Messages published by other clients
// while this client is disconnected will be delivered to it upon reconnection, so long as
// the connection was resumed within 2 minutes. After 2 minutes have elapsed, recovery is no longer possible
// and the connection will move to the SUSPENDED state.
var ConnectionEventDisconnected = ably.ConnectionEventDisconnected

// ConnectionEventSuspended - A long term failure condition. No current connection exists
// because there is no network connectivity or no host is available. The suspended state is entered
// after a failed connection attempt if there has then been no connection for a period of two minutes.
// In the suspended state, the library will periodically attempt to open a new connection every 30 seconds.
// Developers are unable to publish messages in this state. A new connection attempt can also be triggered
// by an explicit call to Connection.Connect. Once the connection has been re-established,
// channels will be automatically re-attached. The client has been disconnected for too long for them
// to resume from where they left off, so if it wants to catch up on messages published by other clients
// while it was disconnected, it needs to use the History API.
var ConnectionEventSuspended = ably.ConnectionEventSuspended

// ConnectionEventClosing is when an explicit request by the developer to close the connection has been sent to
// the Ably service. If a reply is not received from Ably within a short period of time,
// the connection is forcibly terminated and the connection state becomes CLOSED.
var ConnectionEventClosing = ably.ConnectionEventClosing

// ConnectionEventClosed - The connection has been explicitly closed by the client.
// In the closed state, no reconnection attempts are made automatically by the library,
// and clients may not publish messages. No connection state is preserved by the service or by the library.
// A new connection attempt can be triggered by an explicit call to Connection.Connect,
// which results in a new connection.
var ConnectionEventClosed = ably.ConnectionEventClosed

// ConnectionEventFailed - This state is entered if the client library encounters a failure condition
// that it cannot recover from. This may be a fatal connection error received from the Ably service,
// for example an attempt to connect with an incorrect API key, or a local terminal error,
// for example the token in use has expired and the library does not have any way to renew it.
// In the failed state, no reconnection attempts are made automatically by the library, and
// clients may not publish messages. A new connection attempt can be triggered by an explicit call
// to Connection.Connect.
var ConnectionEventFailed = ably.ConnectionEventFailed

// ConnectionEventUpdate is an event for changes to connection conditions for which the
// [ConnectionState] does not change (RTN4h).
var ConnectionEventUpdate = ably.ConnectionEventUpdate

// ChannelStateInitialized is when the channel has been initialized but no attach has yet been attempted.
var ChannelStateInitialized = ably.ChannelStateInitialized

// ChannelStateAttaching is when the attach has been initiated by sending a request to Ably.
// This is a transient state, followed either by a transition to ATTACHED, SUSPENDED, or FAILED.
var ChannelStateAttaching = ably.ChannelStateAttaching

// ChannelStateAttached is when the attach has succeeded.
// In the ATTACHED state a client may publish and subscribe to messages, or be present on the channel.
var ChannelStateAttached = ably.ChannelStateAttached

// ChannelStateDetaching is when a detach has been initiated on an ATTACHED channel by sending a request to Ably.
// This is a transient state, followed either by a transition to DETACHED or FAILED.
var ChannelStateDetaching = ably.ChannelStateDetaching

// ChannelStateDetached os when the channel, having previously been ATTACHED, has been detached by the user.
var ChannelStateDetached = ably.ChannelStateDetached

// ChannelStateSuspended is when the channel, having previously been ATTACHED, has lost continuity,
// usually due to the client being disconnected from Ably for longer than two minutes.
// It will automatically attempt to reattach as soon as connectivity is restored.
var ChannelStateSuspended = ably.ChannelStateSuspended

// ChannelStateFailed is an indefinite failure condition.
// This state is entered if a channel error has been received from the Ably service,
// such as an attempt to attach without the necessary access rights.
var ChannelStateFailed = ably.ChannelStateFailed

// ChannelEventInitialized is when the channel has been initialized but no attach has yet been attempted.
var ChannelEventInitialized = ably.ChannelEventInitialized

// ChannelEventAttaching is when the attach has been initiated by sending a request to Ably.
// This is a transient state, followed either by a transition to ATTACHED, SUSPENDED, or FAILED.
var ChannelEventAttaching = ably.ChannelEventAttaching

// ChannelEventAttached is when the attach has succeeded.
// In the ATTACHED state a client may publish and subscribe to messages, or be present on the channel.
var ChannelEventAttached = ably.ChannelEventAttached

// ChannelEventDetaching is when a detach has been initiated on an ATTACHED channel by sending a request to Ably.
// This is a transient state, followed either by a transition to DETACHED or FAILED.
var ChannelEventDetaching = ably.ChannelEventDetaching

// ChannelEventDetached os when the channel, having previously been ATTACHED, has been detached by the user.
var ChannelEventDetached = ably.ChannelEventDetached

// ChannelEventSuspended is when the channel, having previously been ATTACHED, has lost continuity,
// usually due to the client being disconnected from Ably for longer than two minutes.
// It will automatically attempt to reattach as soon as connectivity is restored.
var ChannelEventSuspended = ably.ChannelEventSuspended

// ChannelEventFailed is an indefinite failure condition.
// This state is entered if a channel error has been received from the Ably service,
// such as an attempt to attach without the necessary access rights.
var ChannelEventFailed = ably.ChannelEventFailed

// ChannelEventUpdate is an event for changes to channel conditions that do not result
// in a change in [ChannelState] (RTL2g).
var ChannelEventUpdate = ably.ChannelEventUpdate

// Functions.

// AgentIdentifier returns the value the library sends in the Ably-Agent header
// (RSC7d) for the given additional agents. It is exported so that test helpers
// can identify their own requests to Ably with the same agent string the client
// uses, without duplicating the library version.
func AgentIdentifier(agents map[string]string) string {
	return ably.AgentIdentifier(agents)
}

// AuthWithCallback is used for setting AuthCallback function using [AuthOption].
//
// AuthCallback function is called when a new token is required.
// The role of the callback is to obtain a fresh token, one of
//
//  1. An Ably Token string (https://ably.com/docs/core-features/authentication#token-process)
//  2. A signed [TokenRequest] (https://ably.com/docs/core-features/authentication#token-request-process)
//  3. An [TokenDetails] (https://ably.com/docs/core-features/authentication#token-process)
//  4. [An Ably JWT].
//
// See the [authentication doc] for more details and associated API calls (RSA4a, RSA4, TO3j5, AO2b).
//
// [authentication doc]: https://ably.com/docs/core-features/authentication
// [An Ably JWT]: https://ably.com/docs/core-features/authentication#ably-jwt-process
func AuthWithCallback(authCallback func(a0 context.Context, a1 TokenParams) (Tokener, error)) AuthOption {
	return ably.AuthWithCallback(authCallback)
}

// AuthWithDefaultTokenParams is used for setting DefaultTokenParams token using [AuthOption].
// DefaultTokenParams when provided, it overrides the client library defaults when issuing new Ably Tokens
// for multiple Ably [TokenRequest] (TO3j11).
func AuthWithDefaultTokenParams(params TokenParams) AuthOption {
	return ably.AuthWithDefaultTokenParams(params)
}

// AuthWithHeaders is used for setting AuthHeaders using [AuthOption].
// AuthHeaders are key-value pair HTTP request headers to be added to any request made to the AuthURL.
// Useful when an application requires these to be added to validate the request or implement the response.
// If the authHeaders object contains an authorization key, then withCredentials is set on the XHR request.
// (RSA8c3, TO3j8, AO2e).
func AuthWithHeaders(headers http.Header) AuthOption {
	return ably.AuthWithHeaders(headers)
}

// AuthWithKey is used for setting root/non-root apikey using [AuthOption].
// Key is a full API key string, as obtained from the Ably dashboard.
// Use this option if you wish to use Basic authentication, or wish to be able to issue Ably Tokens
// without needing to defer to a separate entity to sign multiple [TokenRequest].
// Read more about [Basic authentication] (RSA11, RSA14, TO3j1, AO2a).
//
// [Basic authentication]: https://ably.com/docs/core-features/authentication#basic-authentication
func AuthWithKey(key string) AuthOption {
	return ably.AuthWithKey(key)
}

// AuthWithMethod is used for setting AuthMethod using [AuthOption]
// AuthMethod specifies HTTP verb to use for any request made to the AuthURL, either GET or POST for
// getting token information [TokenRequest] or [TokenDetails].
// The default value is GET (RSA8c, TO3j7, AO2d).
func AuthWithMethod(method string) AuthOption {
	return ably.AuthWithMethod(method)
}

// AuthWithParams is used for setting AuthParams using [AuthOption].
// AuthParams are key-value pair HTTP query params to be added to any request made to the AuthURL.
// When the authMethod is GET, query params are added to the URL, whereas when authMethod is POST,
// the params are sent as URL encoded form data. Useful when an application requires these to be added to
// validate the request or implement the response (RSA8c3, RSA8c1, TO3j9, AO2f).
func AuthWithParams(params url.Values) AuthOption {
	return ably.AuthWithParams(params)
}

// AuthWithQueryTime is used for setting UseQueryTime token using [AuthOption].
// UseQueryTime when set to true, the library queries the Ably servers for the current time when
// issuing multiple [TokenRequest] instead of relying on a locally-available time of day.
// Knowing the time accurately is needed to create valid signed Ably [TokenRequest],
// so this option is useful for library instances on auth servers where for some reason
// the server clock cannot be kept synchronized through normal means,
// such as an NTP daemon. The server is queried for the current time once per client library instance
// (which stores the offset from the local clock), so if using this option you should avoid instancing
// a new version of the library for each request.
// The default is false (RSA9d, TO3j10, AO2a).
func AuthWithQueryTime(queryTime bool) AuthOption {
	return ably.AuthWithQueryTime(queryTime)
}

// AuthWithToken is used for setting authenticated token using [AuthOption].
// This can either be a token string (obtained from the token property of a [TokenDetails] component of
// an Ably [TokenRequest] response, or a JSON Web Token satisfying the Ably requirements for JWTs).
//
// This option is mostly useful for testing: since tokens are short-lived,
// in production you almost always want to use an authentication method that enables the client library
// to renew the token automatically when the previous one expires, such as AuthURL or authCallback.
// Read more about [Token authentication] (RSA4a, RSA4, TO3j2).
//
// [Token authentication]: https://ably.com/docs/core-features/authentication#token-authentication
func AuthWithToken(token string) AuthOption {
	return ably.AuthWithToken(token)
}

// AuthWithTokenDetails is used for setting authenticated [TokenDetails] object using [AuthOption].
// Only TokenDetails.Token can be set via token string (obtained from the token property of a [TokenDetails]
// component of an Ably [TokenRequest] response, or a JSON Web Token satisfying the Ably requirements for JWTs).
// This option is mostly useful for testing: since tokens are short-lived,
// in production you almost always want to use an authentication method that enables the client library
// to renew the token automatically when the previous one expires, such as AuthURL or authCallback.
// Read more about [Token authentication] (RSA4a, RSA4, TO3j3).
//
// [Token authentication]: https://ably.com/docs/core-features/authentication#token-authentication
func AuthWithTokenDetails(details *TokenDetails) AuthOption {
	return ably.AuthWithTokenDetails(details)
}

// AuthWithURL is used for setting AuthURL using [AuthOption].
// AuthURL is a url that library will use to obtain
//  1. An Ably Token string (https://ably.com/docs/core-features/authentication#token-process)
//  2. A signed [TokenRequest] (https://ably.com/docs/core-features/authentication#token-request-process)
//  3. An [TokenDetails] (https://ably.com/docs/core-features/authentication#token-process)
//  4. [An Ably JWT].
//
// See the [authentication doc] for more details and associated API calls (RSA4a, RSA4, RSA8c, TO3j6, AO2c).
//
// This enables a client to obtain token requests from another entity,
// so tokens can be renewed without the client requiring access to keys.
//
// If AuthURL is non-empty and AuthCallback is nil, the Ably library
// builds a req (*http.Request) which then is issued against the given AuthURL
// in order to obtain authentication token. The response is expected to
// carry a single token string in the payload when Content-Type header
// is "text/plain" or JSON-encoded *TokenDetails when the header
// is "application/json".
//
// The req is built with the following values:
//
// GET requests:
//
//   - req.URL.RawQuery is encoded from *TokenParams and AuthParams
//   - req.Header is set to AuthHeaders
//
// POST requests:
//
//   - req.Header is set to AuthHeaders
//   - Content-Type is set to "application/x-www-form-urlencoded" and
//     the payload is encoded from *TokenParams and AuthParams
//
// [authentication doc]: https://ably.com/docs/core-features/authentication
// [An Ably JWT]: https://ably.com/docs/core-features/authentication#ably-jwt-process
func AuthWithURL(url string) AuthOption {
	return ably.AuthWithURL(url)
}

// AuthWithUseTokenAuth is used for setting UseTokenAuth using [AuthOption].
// UseTokenAuth when set to true, forces token authentication to be used by the library.
// If a clientId is not specified in the [ClientOption] or [TokenParams],
// then the Ably Token issued is anonymous (RSA4, RSA14, TO3j4).
func AuthWithUseTokenAuth(use bool) AuthOption {
	return ably.AuthWithUseTokenAuth(use)
}

// ChannelWithCipher requests encryption for this channel when not null, and specifies encryption-related parameters
// (such as algorithm, chaining mode, key length and key). See [an example] (RSL5a, TB2b).
//
// [an example]: https://ably.com/docs/realtime/encryption#getting-started
func ChannelWithCipher(params CipherParams) ChannelOption {
	return ably.ChannelWithCipher(params)
}

// ChannelWithCipherKey is a constructor that takes private key as a argument.
// It is used to encrypt and decrypt payloads (TB3)
func ChannelWithCipherKey(key []byte) ChannelOption {
	return ably.ChannelWithCipherKey(key)
}

// ChannelWithModes set an array of [ChannelMode] to a channel (TB2d).
func ChannelWithModes(modes ...ChannelMode) ChannelOption {
	return ably.ChannelWithModes(modes...)
}

// ChannelWithParams sets channel parameters that configure the behavior of the channel (TB2c).
func ChannelWithParams(key string, value string) ChannelOption {
	return ably.ChannelWithParams(key, value)
}

// ChannelWithVCDiff sets channel parameters for VCDIFF delta compression.
// This is a convenience method that internally sets "delta" to "vcdiff" parameters.
func ChannelWithVCDiff() ChannelOption {
	return ably.ChannelWithVCDiff()
}

func DecodeRecoveryKey(recoveryKey string) (*RecoveryKeyContext, error) {
	return ably.DecodeRecoveryKey(recoveryKey)
}

// DefaultCipherParams returns CipherParams with fields set to default values.
// This generates random secret key and iv values
func DefaultCipherParams() (*CipherParams, error) {
	return ably.DefaultCipherParams()
}

// GetPresenceWithClientID filters the list of returned presence members by a specific client using its ID (RSP3a2).
func GetPresenceWithClientID(clientID string) GetPresenceOption {
	return ably.GetPresenceWithClientID(clientID)
}

// GetPresenceWithConnectionID filters the list of returned presence members by a specific connection using its ID.
// RSP3a3
func GetPresenceWithConnectionID(connectionID string) GetPresenceOption {
	return ably.GetPresenceWithConnectionID(connectionID)
}

// GetPresenceWithLimit sets an upper limit on the number of messages returned.
// The default is 100, and the maximum is 1000 (RSP3a).
func GetPresenceWithLimit(limit int) GetPresenceOption {
	return ably.GetPresenceWithLimit(limit)
}

// HistoryWithDirection sets the order for which messages are returned in.
// Valid values are backwards which orders messages from most recent to oldest,
// or forwards which orders messages from oldest to most recent.
// The default is backwards (RSL2b2).
func HistoryWithDirection(d Direction) HistoryOption {
	return ably.HistoryWithDirection(d)
}

// HistoryWithEnd sets time until messages are retrieved, specified as milliseconds since the Unix epoch (RSL2b1).
func HistoryWithEnd(t time.Time) HistoryOption {
	return ably.HistoryWithEnd(t)
}

// HistoryWithLimit sets an upper limit on the number of messages returned.
// The default is 100, and the maximum is 1000 (RSL2b3).
func HistoryWithLimit(limit int) HistoryOption {
	return ably.HistoryWithLimit(limit)
}

// HistoryWithStart sets time from which messages are retrieved, specified as milliseconds since the Unix epoch.
// RSL2b1
func HistoryWithStart(t time.Time) HistoryOption {
	return ably.HistoryWithStart(t)
}

// NewVCDiffPlugin creates a new AblyVCDiffDecoder plugin instance.
// Used publicly to set the VCDiff plugin in the client options.
//
// Example:
//
//	client, err := NewHTTPClient(WithVCDiffPlugin(NewVCDiffPlugin()))
func NewVCDiffPlugin() VCDiffDecoder {
	return ably.NewVCDiffPlugin()
}

// PresenceGetWithWaitForSync sets whether to wait for a full presence set synchronization between Ably
// and the clients on the channel to complete before returning the results.
// Synchronization begins as soon as the channel is [ChannelStateAttached].
// When set to true the results will be returned as soon as the sync is complete.
// When set to false the current list of members will be returned without the sync completing.
// The default is true (RTP11c1).
func PresenceGetWithWaitForSync(wait bool) PresenceGetOption {
	return ably.PresenceGetWithWaitForSync(wait)
}

// PresenceHistoryWithDirection sets the order for which messages are returned in.
// Valid values are backwards which orders messages from most recent to oldest,
// or forwards which orders messages from oldest to most recent.
// The default is backwards (RSP4b2).
func PresenceHistoryWithDirection(d Direction) PresenceHistoryOption {
	return ably.PresenceHistoryWithDirection(d)
}

// PresenceHistoryWithEnd sets the time until messages are retrieved, specified as milliseconds since the Unix epoch.
// (RSP4b1)
func PresenceHistoryWithEnd(t time.Time) PresenceHistoryOption {
	return ably.PresenceHistoryWithEnd(t)
}

// PresenceHistoryWithLimit sets an upper limit on the number of messages returned.
// The default is 100, and the maximum is 1000 (RSP4b3).
func PresenceHistoryWithLimit(limit int) PresenceHistoryOption {
	return ably.PresenceHistoryWithLimit(limit)
}

// PresenceHistoryWithStart sets the time from which messages are retrieved, specified as milliseconds
// since the Unix epoch (RSP4b1).
func PresenceHistoryWithStart(t time.Time) PresenceHistoryOption {
	return ably.PresenceHistoryWithStart(t)
}

// Deprecated: Use PublishWithParams instead.
// PublishMultipleWithParams is the same as PublishWithParams.
//
// TODO: Remove this in the next major version bump to 2.x.x.
func PublishMultipleWithParams(params map[string]string) PublishMultipleOption {
	return ably.PublishMultipleWithParams(params)
}

// PublishWithConnectionKey allows a message to be published for a specified connectionKey.
func PublishWithConnectionKey(connectionKey string) PublishMultipleOption {
	return ably.PublishWithConnectionKey(connectionKey)
}

// PublishWithParams adds query parameters to the resulting HTTP request to the REST API.
func PublishWithParams(params map[string]string) PublishMultipleOption {
	return ably.PublishWithParams(params)
}

// RequestWithBody sets the JSON body of the request.
func RequestWithBody(body interface{}) RequestOption {
	return ably.RequestWithBody(body)
}

// RequestWithHeaders sets additional HTTP headers to include in the request.
func RequestWithHeaders(headers http.Header) RequestOption {
	return ably.RequestWithHeaders(headers)
}

// RequestWithParams sets the parameters to include in the URL query of the request.
// The parameters depend on the endpoint being queried.
// See the REST API reference for the available parameters of each endpoint.
func RequestWithParams(params url.Values) RequestOption {
	return ably.RequestWithParams(params)
}

// StatsWithDirection sets the order for which stats are returned in. Valid values are backwards which
// orders stats from most recent to oldest, or forwards which orders stats from oldest to most recent.
// The default is backwards (RSC6b2).
func StatsWithDirection(d Direction) StatsOption {
	return ably.StatsWithDirection(d)
}

// StatsWithEnd sets the time until stats are retrieved, specified as milliseconds since the Unix epoch (RSC6b1).
func StatsWithEnd(t time.Time) StatsOption {
	return ably.StatsWithEnd(t)
}

// StatsWithLimit sets an upper limit on the number of stats returned.
// The default is 100, and the maximum is 1000 (RSC6b3).
func StatsWithLimit(limit int) StatsOption {
	return ably.StatsWithLimit(limit)
}

// StatsWithStart sets the time from which stats are retrieved, specified as milliseconds since the Unix epoch (RSC6b1).
func StatsWithStart(t time.Time) StatsOption {
	return ably.StatsWithStart(t)
}

// StatsWithUnit sets minute, hour, day or month. Based on the unit selected, the given start or end times are
// rounded down to the start of the relevant interval depending on the unit granularity of the query (RSC6b4).
func StatsWithUnit(d PeriodUnit) StatsOption {
	return ably.StatsWithUnit(d)
}

// UpdateWithClientID sets the client ID for the update operation.
func UpdateWithClientID(clientID string) UpdateOption {
	return ably.UpdateWithClientID(clientID)
}

// UpdateWithDescription sets a description for the update operation.
func UpdateWithDescription(description string) UpdateOption {
	return ably.UpdateWithDescription(description)
}

// UpdateWithMetadata sets metadata for the update operation.
func UpdateWithMetadata(metadata map[string]string) UpdateOption {
	return ably.UpdateWithMetadata(metadata)
}

// UpdateWithParams sets operation params. When using REST, these are included as URL query
// parameters (RSL15a, RSL15f). When using Realtime, these are set as protocolMessage.Params (RTL32e).
func UpdateWithParams(params map[string]string) UpdateOption {
	return ably.UpdateWithParams(params)
}

// WithAgents is used to add product/version key-value pairs to include in the
// agent library identifiers. This must only be used by Ably-authored SDKs.
// Successive calls merge their entries into any agents already configured
// rather than replacing them.
func WithAgents(agents map[string]string) ClientOption {
	return ably.WithAgents(agents)
}

// WithAuthCallback is used for setting authCallback function using [ClientOption].
// AuthCallback function is called when a new token is required.
// The role of the callback is to obtain a fresh token, one of
//
//  1. An Ably Token string (https://ably.com/docs/core-features/authentication#token-process)
//  2. A signed [TokenRequest] (https://ably.com/docs/core-features/authentication#token-request-process)
//  3. An [TokenDetails] (https://ably.com/docs/core-features/authentication#token-process)
//  4. [An Ably JWT].
//
// See the [authentication doc] for more details and associated API calls (RSA4a, RSA4, TO3j5, AO2b).
//
// [authentication doc]: https://ably.com/docs/core-features/authentication
// [An Ably JWT]: https://ably.com/docs/core-features/authentication#ably-jwt-process
func WithAuthCallback(authCallback func(a0 context.Context, a1 TokenParams) (Tokener, error)) ClientOption {
	return ably.WithAuthCallback(authCallback)
}

// WithAuthHeaders is used for setting AuthHeaders using [ClientOption].
// AuthHeaders are key-value pair HTTP request headers to be added to any request made to the AuthURL.
// Useful when an application requires these to be added to validate the request or implement the response.
// If the authHeaders object contains an authorization key, then withCredentials is set on the XHR request.
// (RSA8c3, TO3j8, AO2e).
func WithAuthHeaders(headers http.Header) ClientOption {
	return ably.WithAuthHeaders(headers)
}

// WithAuthMethod is used for setting AuthMethod using [ClientOption].
// AuthMethod specifies HTTP verb to use for any request made to the AuthURL, either GET or POST for
// getting token information [TokenRequest] or [TokenDetails].
// The default value is GET (RSA8c, TO3j7, AO2d)
func WithAuthMethod(method string) ClientOption {
	return ably.WithAuthMethod(method)
}

// WithAuthParams is used for setting AuthParams using [ClientOption].
// AuthParams are key-value pair HTTP query params to be added to any request made to the AuthURL.
// When the authMethod is GET, query params are added to the URL, whereas when authMethod is POST,
// the params are sent as URL encoded form data. Useful when an application requires these to be added to
// validate the request or implement the response (RSA8c3, RSA8c1, TO3j9, AO2f).
func WithAuthParams(params url.Values) ClientOption {
	return ably.WithAuthParams(params)
}

// WithAuthURL is used for setting AuthURL using [ClientOption].
// AuthURL is a url that library will use to obtain
//  1. An Ably Token string (https://ably.com/docs/core-features/authentication#token-process)
//  2. A signed [TokenRequest] (https://ably.com/docs/core-features/authentication#token-request-process)
//  3. An [TokenDetails] (https://ably.com/docs/core-features/authentication#token-process)
//  4. [An Ably JWT].
//
// See the [authentication doc] for more details and associated API calls (RSA4a, RSA4, RSA8c, TO3j6, AO2c).
//
// This enables a client to obtain token requests from another entity,
// so tokens can be renewed without the client requiring access to keys.
//
// If AuthURL is non-empty and AuthCallback is nil, the Ably library
// builds a req (*http.Request) which then is issued against the given AuthURL
// in order to obtain authentication token. The response is expected to
// carry a single token string in the payload when Content-Type header
// is "text/plain" or JSON-encoded *TokenDetails when the header
// is "application/json".
//
// The req is built with the following values:
//
// GET requests:
//
//   - req.URL.RawQuery is encoded from *TokenParams and AuthParams
//   - req.Header is set to AuthHeaders
//
// POST requests:
//
//   - req.Header is set to AuthHeaders
//   - Content-Type is set to "application/x-www-form-urlencoded" and
//     the payload is encoded from *TokenParams and AuthParams
//
// [authentication doc]: https://ably.com/docs/core-features/authentication
// [An Ably JWT]: https://ably.com/docs/core-features/authentication#ably-jwt-process
func WithAuthURL(url string) ClientOption {
	return ably.WithAuthURL(url)
}

// WithAutoConnect is used for setting NoConnect using [ClientOption].
// NoConnect when set to false, the client connects to Ably as soon as it is instantiated.
// You can set this to true and explicitly connect to Ably using the [Connection]#connect()
// The default is false (RTC1b, TO3e).
func WithAutoConnect(autoConnect bool) ClientOption {
	return ably.WithAutoConnect(autoConnect)
}

// WithChannelRetryTimeout is used for setting ChannelRetryTimeout using [ClientOption].
// ChannelRetryTimeout when a channel becomes [ChannelStateSuspended} following a server initiated
// [ChannelStateDetached], after this delay, if the channel is still [ChannelStateSuspended]
// and the connection is in [ConnectionStateConnected], the client library will attempt to re-attach
// the channel automatically.
// The default is 15 seconds (RTL13b, TO3l7).
func WithChannelRetryTimeout(d time.Duration) ClientOption {
	return ably.WithChannelRetryTimeout(d)
}

// WithClientID is used for setting ClientID using [ClientOption].
// ClientID is used for identifying this client when publishing messages or for presence purposes.
// The clientId can be any non-empty string, except it cannot contain a *.
// This option is primarily intended to be used in situations where the library is instantiated with a key.
// Note that a clientId may also be implicit in a token used to instantiate the library.
// An error will be raised if a clientId specified here conflicts with the clientId implicit in the token.
// (RSC17, RSA4, RSA15, TO3a).
func WithClientID(clientID string) ClientOption {
	return ably.WithClientID(clientID)
}

// WithDefaultTokenParams is used for setting DefaultTokenParams token using [ClientOption].
// DefaultTokenParams when provided, it overrides the client library defaults when issuing new Ably Tokens
// for multiple Ably [TokenRequest] (TO3j11).
func WithDefaultTokenParams(params TokenParams) ClientOption {
	return ably.WithDefaultTokenParams(params)
}

// WithDisconnectedRetryTimeout is used for setting DisconnectedRetryTimeout using [ClientOption].
// DisconnectedRetryTimeout when the connection enters the [ConnectionStateDisconnected] state, after this
// timeout, if the state is still [ConnectionStateDisconnected], the client library will attempt
// to reconnect automatically.
// The default is 15 seconds (TO3l1).
func WithDisconnectedRetryTimeout(d time.Duration) ClientOption {
	return ably.WithDisconnectedRetryTimeout(d)
}

// WithEchoMessages is used for setting NoEcho using [ClientOption].
// NoEcho if set to true, prevents messages originating from this connection being echoed back
// on the same connection.
// The default is false (RTC1a, TO3h).
func WithEchoMessages(echo bool) ClientOption {
	return ably.WithEchoMessages(echo)
}

// WithEndpoint sets a custom endpoint for connecting to the Ably service (see
// [Platform Customization] for more information).
//
// [Platform Customization]: https://ably.com/docs/platform-customization
func WithEndpoint(env string) ClientOption {
	return ably.WithEndpoint(env)
}

// WithEnvironment sets a custom endpoint for connecting to the Ably service
// (see [Platform Customization] for more information).
//
// Deprecated: this option is deprecated and will be removed in a future
// version.
//
// [Platform Customization]: https://ably.com/docs/platform-customization
func WithEnvironment(env string) ClientOption {
	return ably.WithEnvironment(env)
}

// WithExperimentalObjectsPlugin configures the client to use the given plugin to implement
// [LiveObjects] functionality.
//
// NOTE: this option is experimental, the LiveObjects plugin API may change in a
// backwards incompatible way between minor/patch versions. Once the API has been finalised,
// a new non-experimental option will be added, and this one will be removed.
//
// [LiveObjects]: https://ably.com/docs/liveobjects
func WithExperimentalObjectsPlugin(plugin ObjectsPlugin) ClientOption {
	return ably.WithExperimentalObjectsPlugin(plugin)
}

// WithFallbackHosts is used for setting FallbackHosts using [ClientOption].
// FallbackHosts is an array of fallback hosts to be used in the case of an error necessitating
// the use of an alternative host. If you have been provided a set of custom fallback hosts by Ably,
// please specify them here (RSC15b, RSC15a, TO3k6).
func WithFallbackHosts(hosts []string) ClientOption {
	return ably.WithFallbackHosts(hosts)
}

// Deprecated: This function is deprecated and will be removed in a future versions.
// WithFallbackHostsUseDefault is used for setting FallbackHostsUseDefault using [ClientOption].
// Deprecated: this property is deprecated and will be removed in a future version.
// Enables default fallback hosts to be used (TO3k7).
func WithFallbackHostsUseDefault(fallbackHostsUseDefault bool) ClientOption {
	return ably.WithFallbackHostsUseDefault(fallbackHostsUseDefault)
}

// WithFallbackRetryTimeout is used for setting FallbackRetryTimeout using [ClientOption].
// FallbackRetryTimeout is the max time in milliseconds before HTTP requests are retried against the default endpoint.
// The default is 600 seconds (TO3l10).
func WithFallbackRetryTimeout(fallbackRetryTimeout time.Duration) ClientOption {
	return ably.WithFallbackRetryTimeout(fallbackRetryTimeout)
}

// WithHTTPClient is used for setting HTTPClient using [ClientOption].
// HTTPClient specifies the client used for HTTP communication by [HTTPClient].
// When set to nil, a client configured with default settings is used.
func WithHTTPClient(client *http.Client) ClientOption {
	return ably.WithHTTPClient(client)
}

// WithHTTPHost is used for setting HTTPHost using [ClientOption].
// HTTPHost enables a non-default Ably host to be specified. For development environments only.
// The default value is rest.ably.io (RSC12, TO3k2).
//
// Deprecated: this option is deprecated and will be removed in a future
// version.
func WithHTTPHost(host string) ClientOption {
	return ably.WithHTTPHost(host)
}

// WithHTTPMaxRetryCount is used for setting HTTPMaxRetryCount using [ClientOption].
// HTTPMaxRetryCount denotes the maximum number of fallback hosts to use as a fallback when an HTTP request
// to the primary host is unreachable or indicates that it is unserviceable. The default value is 3 (TO3l5).
func WithHTTPMaxRetryCount(count int) ClientOption {
	return ably.WithHTTPMaxRetryCount(count)
}

// WithHTTPOpenTimeout is used for setting HTTPOpenTimeout using [ClientOption].
// HTTPOpenTimeout is timeout for opening a connection to Ably to initiate an HTTP request.
// The default is 4 seconds (TO3l3).
func WithHTTPOpenTimeout(d time.Duration) ClientOption {
	return ably.WithHTTPOpenTimeout(d)
}

// WithHTTPRequestTimeout is used for setting HTTPRequestTimeout using [ClientOption].
// HTTPRequestTimeout is a timeout for a client performing a complete HTTP request to Ably, including the connection phase.
// Will only be used if no custom HTTPClient is set.
// The default is 10 seconds (TO3l4).
func WithHTTPRequestTimeout(timeout time.Duration) ClientOption {
	return ably.WithHTTPRequestTimeout(timeout)
}

// WithIdempotentHTTPPublishing is used for setting IdempotentHTTPPublishing using [ClientOption].
// IdempotentHTTPPublishing when set to true, enables idempotent publishing by assigning a
// unique message ID client-side, allowing the Ably servers to discard automatic publish retries
// following a failure such as a network fault.
// The default is true (RSL1k1, RTL6a1, TO3n).
func WithIdempotentHTTPPublishing(idempotent bool) ClientOption {
	return ably.WithIdempotentHTTPPublishing(idempotent)
}

// WithInsecureAllowBasicAuthWithoutTLS permits an API key to be used even if the connection
// will not use TLS, something which would otherwise not be permitted for security reasons.
func WithInsecureAllowBasicAuthWithoutTLS() ClientOption {
	return ably.WithInsecureAllowBasicAuthWithoutTLS()
}

// WithKey is used for setting root/non-root apikey using [ClientOption].
// Key is a full API key string, as obtained from the Ably dashboard.
// Use this option if you wish to use Basic authentication, or wish to be able to issue Ably Tokens
// without needing to defer to a separate entity to sign multiple [TokenRequest].
// Read more about [Basic authentication] (RSC1, RSA11, RSA14, TO3j1, AO2a).
//
// [Basic authentication]: https://ably.com/docs/core-features/authentication#basic-authentication
func WithKey(key string) ClientOption {
	return ably.WithKey(key)
}

// WithLogHandler is used for setting LogHandler using [ClientOption].
// LogHandler controls the log output of the library. This is a function to handle each line of log output.
// platform specific (TO3c)
func WithLogHandler(handler Logger) ClientOption {
	return ably.WithLogHandler(handler)
}

// WithLogLevel is used for setting LogLevel using [ClientOption].
// LogLevel controls the verbosity of the logs output from the library.
// Levels include verbose, debug, info, warn and error.
// platform specific (TO3b)
func WithLogLevel(level LogLevel) ClientOption {
	return ably.WithLogLevel(level)
}

// WithPort is used for setting custom Port using [ClientOption].
// Port is used for non-TLS connections and requests
func WithPort(port int) ClientOption {
	return ably.WithPort(port)
}

// WithQueryTime is used for setting UseQueryTime token using [ClientOption].
// UseQueryTime when set to true, the library queries the Ably servers for the current time when
// issuing multiple [TokenRequest] instead of relying on a locally-available time of day.
// Knowing the time accurately is needed to create valid signed Ably [TokenRequest],
// so this option is useful for library instances on auth servers where for some reason
// the server clock cannot be kept synchronized through normal means,
// such as an NTP daemon. The server is queried for the current time once per client library instance
// (which stores the offset from the local clock), so if using this option you should avoid instancing
// a new version of the library for each request.
// The default is false (RSA9d, TO3j10, AO2a).
func WithQueryTime(queryTime bool) ClientOption {
	return ably.WithQueryTime(queryTime)
}

// WithQueueMessages is used for setting NoQueueing using [ClientOption].
// NoQueueing if set to true, this disables the default behavior whereby the library queues messages on a
// connection in the disconnected or connecting states. The default behavior enables applications to
// submit messages immediately upon instantiating the library without having to wait for the connection
// to be established. Applications may use this option to disable queueing if they wish to have
// application-level control over the queueing.
// The default is false (RTP16b, TO3g).
func WithQueueMessages(queue bool) ClientOption {
	return ably.WithQueueMessages(queue)
}

// WithRealtimeHost is used for setting RealtimeHost using [ClientOption].
// RealtimeHost enables a non-default Ably host to be specified for realtime connections.
// For development environments only. The default value is realtime.ably.io (RTC1d, TO3k3).
//
// Deprecated: this option is deprecated and will be removed in a future
// version.
func WithRealtimeHost(host string) ClientOption {
	return ably.WithRealtimeHost(host)
}

// WithRealtimeRequestTimeout is used for setting RealtimeRequestTimeout using [ClientOption].
// RealtimeRequestTimeout is the timeout for the wait of acknowledgement for operations performed via a
// realtime connection, before the client library considers a request failed and triggers a failure condition.
// Operations include establishing a connection with Ably, or sending a HEARTBEAT, CONNECT, ATTACH, DETACH or
// CLOSE request. It is the equivalent of httpRequestTimeout but for realtime operations, rather than REST.
// The default is 10 seconds (TO3l11).
func WithRealtimeRequestTimeout(d time.Duration) ClientOption {
	return ably.WithRealtimeRequestTimeout(d)
}

// WithRecover is used for setting Recover using [ClientOption].
// Recover enables a connection to inherit the state of a previous connection that may have existed
// under a different instance of the Realtime library. This might typically be used by clients of the browser
// library to ensure connection state can be preserved when the user refreshes the page.
// A recovery key string can be explicitly provided, or alternatively if a callback function is provided,
// the client library will automatically persist the recovery key between page reloads and call the callback
// when the connection is recoverable. The callback is then responsible for confirming whether the connection
// should be recovered or not. See connection state recovery for further information (RTC1c, TO3i).
func WithRecover(key string) ClientOption {
	return ably.WithRecover(key)
}

// WithSuspendedRetryTimeout is used for setting SuspendedRetryTimeout using [ClientOption].
// SuspendedRetryTimeout is the timeout when the connection enters the [ConnectionStateSuspended] state,
// after this timeout, if the state is still [ConnectionStateSuspended], the client library attempts
// to reconnect automatically.
// The default is 30 seconds (RTN14d, TO3l2).
func WithSuspendedRetryTimeout(d time.Duration) ClientOption {
	return ably.WithSuspendedRetryTimeout(d)
}

// WithTLS is used for setting NoTLS using [ClientOption].
// NoTLS when set to true, the client will use an insecure connection.
// The default is false, meaning a TLS connection will be used to connect to Ably (RSC18, TO3d).
func WithTLS(tls bool) ClientOption {
	return ably.WithTLS(tls)
}

// WithTLSPort is used for setting TLSPort using [ClientOption].
// TLSPort enables a non-default Ably port to be specified.
// This is used for TLS connections and requests and restricted to development environments only.
// The default value is 80 (TO3k4)>
func WithTLSPort(port int) ClientOption {
	return ably.WithTLSPort(port)
}

// WithToken is used for setting authenticated token using [ClientOption].
// This can either be a token string (obtained from the token property of a [TokenDetails] component of
// an Ably [TokenRequest] response, or a JSON Web Token satisfying the Ably requirements for JWTs).
//
// This option is mostly useful for testing: since tokens are short-lived,
// in production you almost always want to use an authentication method that enables the client library
// to renew the token automatically when the previous one expires, such as AuthURL or authCallback.
// Read more about [Token authentication] (RSA4a, RSA4, TO3j2).
//
// [Token authentication]: https://ably.com/docs/core-features/authentication#token-authentication
func WithToken(token string) ClientOption {
	return ably.WithToken(token)
}

// WithTokenDetails is used for setting authenticated [TokenDetails] object using [ClientOption].
// Only TokenDetails.Token can be set via token string (obtained from the token property of a [TokenDetails]
// component of an Ably [TokenRequest] response, or a JSON Web Token satisfying the Ably requirements for JWTs).
// This option is mostly useful for testing: since tokens are short-lived,
// in production you almost always want to use an authentication method that enables the client library
// to renew the token automatically when the previous one expires, such as AuthURL or authCallback.
// Read more about [Token authentication] (RSA4a, RSA4, TO3j3).
//
// [Token authentication]: https://ably.com/docs/core-features/authentication#token-authentication
func WithTokenDetails(details *TokenDetails) ClientOption {
	return ably.WithTokenDetails(details)
}

// WithTransportParams is used for setting TransportParams using [ClientOption].
// TransportParams is a set of key-value pairs that can be used to pass in arbitrary connection parameters,
// such as heartbeatInterval or remainPresentFor (RTC1f).
func WithTransportParams(params url.Values) ClientOption {
	return ably.WithTransportParams(params)
}

// WithUseBinaryProtocol is used for setting NoBinaryProtocol using [ClientOption].
// NoBinaryProtocol when set to true, JSON text encoding is used.
// When false, the more efficient MsgPack binary encoding is used.
// The default is true (TO3f).
func WithUseBinaryProtocol(use bool) ClientOption {
	return ably.WithUseBinaryProtocol(use)
}

// WithUseTokenAuth is used for setting UseTokenAuth using [ClientOption].
// UseTokenAuth when set to true, forces token authentication to be used by the library.
// If a clientId is not specified in the [ClientOption] or [TokenParams],
// then the Ably Token issued is anonymous (RSA4, RSA14, TO3j4).
func WithUseTokenAuth(use bool) ClientOption {
	return ably.WithUseTokenAuth(use)
}

// WithVCDiffPlugin configures the client to use the given plugin to decode vcdiff-encoded
// delta messages (PC3). The plugin must implement the VCDiffDecoder interface.
// This is required for channels that have delta encoding enabled with params {"delta": "vcdiff"}.
func WithVCDiffPlugin(plugin VCDiffDecoder) ClientOption {
	return ably.WithVCDiffPlugin(plugin)
}
