name: Features

on:
  pull_request:
  push:
    branches:
      - main

permissions: {}

jobs:
  build:
    permissions:
      contents: read
    uses: ably/features/.github/workflows/sdk-features.yml@main
    with:
      repository-name: ably-go
    secrets: inherit
